spring:
  datasource:
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
#  flyway:
#    enabled: true
#    url: jdbc:h2:file:./src/main/resources/db/demo
#    user: sa
#    password: 123