create table if not exists product (
    id bigint generated by default as identity,
    cost integer not null,
    title varchar(255) not null,
    primary key (id));
insert into product (cost, title)
values
(11,  'Grapes'),
(16,  'Lime'),
(15,  'Lemon'),
(15,  'Cherry'),
(20,  'Blueberry'),
(13,  'Watermelon'),
(25,  'Peach'),
(27,  'Pineapple'),
(30,  'Strawberry'),
(30,  'Coconut'),
(30,  'Pear'),
(30,  'Apricot'),
(150, 'Avocado'),
(69,  'Blackberry'),
(36,  'Grapefruit'),
(78,  'Kiwi'),
(79,  'Mango'),
(81,  'Plum');


